spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://mysql-master-svc.gulimall:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#    alicloud:
#      access-key:
#      secret-key:
#      oss:
#        endpoint:
#

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false

#  resources:
#    static-locations: classpath:/


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8080
logging:
  level:
    com.atguigu.gulimall: error



