kind: Deployment
apiVersion: apps/v1
metadata:
  name: gulimall-warehouse
  namespace: guilimall
  labels:
    app: gulimall-warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gulimall-warehouse
  template:
    metadata:
      labels:
        app: gulimall-warehouse
    spec:
      containers:
        - name: gulimall-warehouse
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:$PROJECT_VERSION
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: Service
apiVersion: v1
metadata:
  name: gulimall-warehouse
  namespace: guilimall
  labels:
    app: gulimall-warehouse
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 20021
  selector:
    app: gulimall-warehouse
  type: NodePort
  sessionAffinity: None


