spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G9on1ZPjy38eKMZJhDL
      secret-key: w1Yjdsv750WChXzZHfaPW3xnhSqlps
      oss:
        endpoint: oss-us-west-1.aliyuncs.com
        bucket: gulimall-tan

  application:
    name: gulimall-third-party

server:
  port: 30000
